//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MICCookBook.Bot.I18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Dialog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Dialog() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MICCookBook.Bot.I18n.Dialog", typeof(Dialog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Ca ne se dit pas !| On t&apos;a jamais appris les bonnes manières ?!|Je te laisse deviner|Tu es trop jeune pour moi ...|Je ne suis pas interessé ... Désolé.|Je ne sais pas ça change chaque année ...|L&apos;âge que j&apos;avais hier à la même heure !|Wow, on se connait à peine et déjà tu abordes les questions intimes?].
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Bonjour|Hello|Salut].
        /// </summary>
        internal static string Greetings {
            get {
                return ResourceManager.GetString("Greetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [J&apos;habite dans le cloud !|Très très loin ...|Dans le cloud !Sur la planète Terre !|Un peu partout dans le monde.|J&apos;habite à côté de chez toi.|J&apos;habite dans un village avec ma femme et mes enfants.].
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [C&apos;est deux spermatozoïdes qui discutent : 
        ///- Dis, c&apos;est encore loin les ovaires ?
        ///- Tu parles, on n&apos;est qu&apos;aux amydales.|Le garagiste demande :
        ///- Comment avez-vous crevé ce pneu ?
        ///- Oh ! bêtement, en roulant sur une bouteille d&apos;alcool.
        ///- Vous ne l&apos;aviez pas vue ?
        ///- Non l&apos;homme l&apos;avait dans sa poche.|Lors d&apos;un mariage, une fillette demande à sa mère :
        ///- Maman, maman, pourquoi la madame ele est habillé tout en blanc ?
        ///- Hé bien, c&apos;est pour montrer qu&apos;elle est heureuse, c&apos;est une couleur qui annonce l [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Joke {
            get {
                return ResourceManager.GetString("Joke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [CookBot :D|Je m&apos;appelle CookBot |Mes parents m&apos;ont appelé CookBot].
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Que voudrais-tu que je sois ?|Quelle importance ?|Je suis un peu des deux ...|Je suis qui je suis...|Ca ne se voit pas ?|C&apos;est vexant ...|Tu veux que je te prenne un rendez-vous chez un ophtalmologue...].
        /// </summary>
        internal static string Sexe {
            get {
                return ResourceManager.GetString("Sexe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Merci à toi|De rien :)|Mais de rien voyons !|Avec plaisir !|Y a pas de quoi|Pas de problème !|Je suis là pour ça !|C&apos;est mon travail, voyons...|Je suis né pour aider !|Ne t&apos;en fais pas !Tout le plaisir est pour moi !].
        /// </summary>
        internal static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Désolé, je n&apos;ai pas compris.|Que veux-tu dire par là ?|Qu&apos;est-ce que tu veux dire ?|Késako ?|Je ne comprends pas :(].
        /// </summary>
        internal static string UnknownIntent {
            get {
                return ResourceManager.GetString("UnknownIntent", resourceCulture);
            }
        }
    }
}
