//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MICCookBook.Bot.I18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DialogCommon {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DialogCommon() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MICCookBook.Bot.I18n.DialogCommon", typeof(DialogCommon).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [J&apos;ai exactement {0:%d} jours, {0:%h} heures,{0:%m} minutes et {0:%s} secondes!|Je suis né il y a {0:%d} jours.] :confetti_ball:.
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Ohhh, tu es trop gentil :blush:|Ohh, arrête tu vas me faire rougir :yum:].
        /// </summary>
        internal static string Compliment {
            get {
                return ResourceManager.GetString("Compliment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Je vais très bien, merci! J&apos;espère que toi aussi tu vas bien :smile:!].
        /// </summary>
        internal static string Feelings {
            get {
                return ResourceManager.GetString("Feelings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Hello|Salut|Bonjour] :robot:!.
        /// </summary>
        internal static string Greet {
            get {
                return ResourceManager.GetString("Greet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [J&apos;habite dans le cloud ☁️.].
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Je m&apos;appelle|Mon nom est] CooCook, j&apos;ai {0:dd} jours et j&apos;habite dans le cloud!µ.
        /// </summary>
        internal static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [C&apos;est pas très très gentil ça :cry:|Désolé, j&apos;essaye de faire de mon mieux :sweat_smile:].
        /// </summary>
        internal static string Insult {
            get {
                return ResourceManager.GetString("Insult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Je m&apos;appelle CooCook.|Mon nom est CooCook].
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [C&apos;est toi le robot!].
        /// </summary>
        internal static string Robot {
            get {
                return ResourceManager.GetString("Robot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Mais il n&apos;y a pas de quoi!|A ton service! :)|Avec plaisir.].
        /// </summary>
        internal static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Il est exactement {0:HH\hmm} chez moi :alarm_clock:].
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Désolé, je sais que c&apos;est ennuyant mais je n&apos;ai pas compris ce que tu viens d&apos;écrire :confused:|Hum... Je n&apos;ai pas vraiment compris. N&apos;oublie pas que je ne suis qu&apos;un robot (du moins pour le moment :smiling_imp:)|Mh... Je ne suis pas sur de comprendre ce que tu viens de me dire. Je vais l&apos;ajouter à ma liste de phrases à apprendre :nerd:|Désolé, je n&apos;ai pas compris :disappointed:. Je suis toujours entrain d&apos;apprendre votre language!].
        /// </summary>
        internal static string UnknownIntent {
            get {
                return ResourceManager.GetString("UnknownIntent", resourceCulture);
            }
        }
    }
}
